FROM ubuntu:20.04

# Aggiorna i pacchetti e installa le dipendenze
RUN apt-get update && \
    apt-get install -y python3-pip python3.8 openjdk-8-jdk git zip unzip && \
    rm -rf /var/lib/apt/lists/*

# Installazione di buildozer e configurazione
RUN pip3 install buildozer



CMD ["buildozer", "-v", "android", "debug"]
